[build-system]
build-backend = "setuptools.build_meta"
requires = [
	"setuptools >= 77.0.3",
	"wheel",
]

[project]
classifiers = [
	"Development Status :: 4 - Beta",
	"Environment :: Console",
	"Intended Audience :: End Users/Desktop",
	"Programming Language :: Python :: 3 :: Only",
]
dependencies = [
	"Babel",
	"imagesize",
	"jinja2 >= 2.9",
	"pillow >= 6",
	"pycryptodomex",
	"ruamel.yaml < 0.18.0",
	"tqdm",
]
description = "A static website generator that allows you to tell a story with your pictures"
dynamic = [
	"version",
]
license = "GPL-3.0-or-later"
license-files = [
	"LICENSE",
]
maintainers = [
	{name = "Quentin Schulz", email = "foss+recitale@0leil.net"},
]
name = "recitale"
readme = "README.md"
requires-python = ">= 3.0"

[project.optional-dependencies]
tests = [
	"pytest",
	"pytest-cov",
]

[project.scripts]
recitale = "recitale.recitale:main"

[project.urls]
Documentation = "https://recitale.readthedocs.io/"
Homepage = "https://github.com/recitale/recitale"
Issues = "https://github.com/recitale/recitale/issues"
Repository = "https://github.com/recitale/recitale.git"

[tool.setuptools]
packages = [
	"recitale",
]

[tool.setuptools.dynamic]
version = {attr = "recitale.__version__"}

[tool.tox]
envlist = [
	"bandit",
	"check-manifest",
	"pytest",
	"ruff-check",
	"ruff-format-diff",
]

[tool.tox.env.bandit]
basepython = [
	"python3",
]
commands = [
	# B404:import_subprocess Severity: Low Confidence: High => recitale should avoid using subprocess but for now the code is shlex'ed so ~safe
	# B603:subprocess_without_shell_equals_true Severity: Low Confidence: High => see B404
	# B701:jinja2_autoescape_false Severity: High Confidence: High => including HTML code from settings.yaml is a feature of recitale though highly unsecure. TODO: Find much safer work-around
	["bandit", "-s", "B404,B603,B701", "-r", "recitale",],
]
deps = [
	"bandit",
]
skip_install = true

[tool.tox.env.check-manifest]
commands = [
	["{envpython}", "-m", "check_manifest", "{tox_root}",],
]
deps = [
	"check-manifest",
]
no_package = true
skip_install = true

[tool.tox.env.pytest]
basepython = [
	"python3",
]
commands = [
	["pytest", "--cov={envsitepackagesdir}/recitale/", "--cov-report=xml",],
]
extras = [
	"tests",
]

[tool.tox.env.ruff-check]
basepython = [
	"python3",
]
commands = [
	["ruff", "check", ".",],
]
deps = [
	"ruff",
]
skip_install = true

[tool.tox.env.ruff-check-fix]
basepython = [
	"python3",
]
commands = [
	["ruff", "check", "--fix", ".",],
]
deps = [
	"ruff",
]
skip_install = true

[tool.tox.env.ruff-format-diff]
basepython = [
	"python3",
]
commands = [
	["ruff", "format", "--check", "--diff", ".",],
]
deps = [
	"ruff",
]
skip_install = true

[tool.tox.env.ruff-format-fix]
basepython = [
	"python3",
]
commands = [
	["ruff", "format", ".",],
]
deps = [
	"ruff",
]
skip_install = true
