[build-system]
build-backend = "setuptools.build_meta"
requires = [
	"setuptools >= 80",
	"setuptools_scm[simple] >= 8",
	"wheel",
]

[project]
classifiers = [
	"Development Status :: 4 - Beta",
	"Environment :: Console",
	"Intended Audience :: End Users/Desktop",
	"Programming Language :: Python :: 3 :: Only",
]
dependencies = [
	"Babel",
	"jinja2 >= 2.9",
	"pillow >= 6",
	"pycryptodomex",
	"ruamel.yaml < 0.18.0",
	"tqdm",
]
description = "A static website generator that allows you to tell a story with your pictures"
dynamic = [
	"version",
]
license = "GPL-3.0-or-later"
license-files = [
	"LICENSE",
]
maintainers = [
	{name = "Quentin Schulz", email = "foss+recitale@0leil.net"},
]
name = "recitale"
readme = "README.md"
requires-python = ">= 3.0"

[project.optional-dependencies]
docs = [
	"sphinx",
	"sphinx_rtd_theme",
]
tests = [
	"pytest",
	"pytest-cov",
]

[project.scripts]
recitale = "recitale.recitale:main"

[project.urls]
Documentation = "https://recitale.readthedocs.io/"
Homepage = "https://github.com/recitale/recitale"
Issues = "https://github.com/recitale/recitale/issues"
Repository = "https://github.com/recitale/recitale.git"

[tool.coverage.report]
exclude_lines = [
	"pragma: no cover",
	"raise NotImplementedError",
	"if __name__ == .__main__.:",
]
ignore_errors = true
show_missing = true

[tool.coverage.run]
branch = true
source = [
	"recitale/",
]

[tool.setuptools]
packages = [
	"recitale",
]

[tool.setuptools_scm]

[tool.tox]
envlist = [
	"bandit",
	"docs",
	"pytest",
	"ruff-check",
	"ruff-format-diff",
]

[tool.tox.env.bandit]
basepython = [
	"python3",
]
commands = [
	# B404:import_subprocess Severity: Low Confidence: High => recitale should avoid using subprocess but for now the code is shlex'ed so ~safe
	# B603:subprocess_without_shell_equals_true Severity: Low Confidence: High => see B404
	# B701:jinja2_autoescape_false Severity: High Confidence: High => including HTML code from settings.yaml is a feature of recitale though highly unsecure. TODO: Find much safer work-around
	["bandit", "-s", "B404,B603,B701", "-r", "recitale",],
]
deps = [
	"bandit",
]
skip_install = true

[tool.tox.env.docs]
allowlist_externals = [
	"make",
]
commands = [
	["make", "-C", "docs/", "html"],
]
extras = [
	"docs",
]

[tool.tox.env.pytest]
basepython = [
	"python3",
]
commands = [
	["pytest", "--cov={envsitepackagesdir}/recitale/", "--cov-report=xml",],
]
extras = [
	"tests",
]

[tool.tox.env.ruff-check]
basepython = [
	"python3",
]
commands = [
	["ruff", "check", ".",],
]
deps = [
	"ruff",
]
skip_install = true

[tool.tox.env.ruff-check-fix]
basepython = [
	"python3",
]
commands = [
	["ruff", "check", "--fix", ".",],
]
deps = [
	"ruff",
]
skip_install = true

[tool.tox.env.ruff-format-diff]
basepython = [
	"python3",
]
commands = [
	["ruff", "format", "--check", "--diff", ".",],
]
deps = [
	"ruff",
]
skip_install = true

[tool.tox.env.ruff-format-fix]
basepython = [
	"python3",
]
commands = [
	["ruff", "format", ".",],
]
deps = [
	"ruff",
]
skip_install = true
