on:
  release:
    types: [published]

jobs:
  pypi-package:
    if: ${{ github.repository == 'recitale/recitale' }}
    runs-on: ubuntu-latest
    name: Build distribution package
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade build
      - name: Build distribution package
        run: python -m build
      - name: Publish package on Pypi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

  notification:
    if: ${{ github.repository == 'recitale/recitale' }}
    needs: pypi-package
    runs-on: ubuntu-latest
    name: Notifications
    steps:
      - name: IRC notification
        uses: Gottox/irc-message-action@v2
        with:
          channel: '#recitale'
          nickname: github-bot
          message: |-
            recitale ${{ github.ref_name }} was just released. See ${{ github.server_url }}/${{ github.repository }}/releases/tag/${{ github.ref_name }} for the release notes.
