on:
  release:
    types: [published]

jobs:
  pypi-package:
    if: ${{ github.repository == 'recitale/recitale' }}
    runs-on: ubuntu-latest
    name: Build distribution package
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade build
      - name: Build distribution package
        run: python -m build
      - name: Publish package on Pypi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

  container:
    if: ${{ github.repository == 'recitale/recitale' }}
    needs: pypi-package
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and export to Docker
        uses: docker/build-push-action@v2
        with:
          build-args: VERSION=${{ github.ref_name }}
          context: containers
          load: true
          pull: true
          tags: ${{ github.repository }}:test
      - name: Minimal test
        run: |
          docker run --rm -v $PWD/example:/var/www ${{ github.repository }}:test build
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          build-args: VERSION=${{ github.ref_name }}
          context: containers
          pull: true
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}

  notification:
    if: ${{ github.repository == 'recitale/recitale' }}
    needs: [pypi-package, container]
    runs-on: ubuntu-latest
    name: Notifications
    steps:
      - name: IRC notification
        uses: Gottox/irc-message-action@v2
        with:
          channel: '#recitale'
          nickname: github-bot
          message: |-
            recitale ${{ github.ref_name }} was just released. See ${{ github.server_url }}/${{ github.repository }}/releases/tag/${{ github.ref_name }} for the release notes.
